package drink.roulette.model

enum class JsonPropertyName(val property: String) {
    QUESTIONS("QUESTIONS"),
    QUESTION_GROUP("QUESTION_GROUP"),
    TYPE("TYPE"),
    ID("ID"),
    QUESTION("QUESTION"),
    ANSWER("ANSWER"),
    SIMPLE_QUESTION_FOR_ALL("SIMPLE_QUESTION_FOR_ALL"),
    PLAYER_DEDICATED_QUESTION("PLAYER_DEDICATED_QUESTION"),
    PLAYER_DEDICATED_CHALLENGE("PLAYER_DEDICATED_CHALLENGE"),
    TWO_PLAYER_DEDICATED_CHALLENGE("TWO_PLAYER_DEDICATED_CHALLENGE"),
    CHALLENGE_FOR_ALL("CHALLENGE_FOR_ALL")

}
