package drink.roulette.viewHolder

enum class ViewType(val type: Int) {
    DEFAULT_ITEM(-1),
    PLAYER_NAME_ITEM(0),
    TWO_PLAYER_CHALLENGE_TYPE(1),
    DEDICATED_PLAYER_CHALLENGE_TYPE(2),
    CHALLENGE_FOR_ALL_TYPE(3),
    QUESTION_FOR_ALL_TYPE(4),
    QUESTION_FOR_PLAYER_TYPE(5),
    ANSWER_TYPE(6),
    END_MESSAGE_TYPE(7)
}
